apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://saloudiallo151_db_user:KF8XpJrMG6QN1GhE@cluster0.bvy5zlc.mongodb.net/?appName=Cluster0"

  JWT_SECRET: "unesecretcletreslongue123"
  PORT: "3000"