apiVersion: v1
kind: Service
metadata:
  name: portfolio-api
  namespace: portfolio
  labels:
    app: portfolio-api
    monitoring: "true"
spec:
  type: NodePort
  selector:
    app: portfolio-api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30300